name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build_package:
    name: Build and test package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - ROS_DISTRO: noetic
            ROS_REPO: main
          - ROS_DISTRO: noetic
            ROS_REPO: testing
    env:
      SDL_VIDEODRIVER: "dummy"
      SDL_AUDIODRIVER: "disk"
    steps:
      - uses: actions/checkout@v3
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{matrix.env}}
