name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build_package:
    name: Build and test with noetic
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: noetic
      - name: Install catkin tool
        run: sudo apt-get install python3-catkin-tools
      - uses: ros-tooling/action-ros-ci@0.3.3
        with:
          package-name: spatial_audio_demo
          target-ros1-distro: noetic
