name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build_package:
    name: Build and test package
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:noetic-desktop-full
    strategy:
      matrix:
        env:
          - ROS_DISTRO: noetic
            ROS_REPO: main
          - ROS_DISTRO: noetic
            ROS_REPO: testing
    steps:
      - uses: actions/checkout@v3
      - name: show audio device
        run: |
          aplay -l
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{matrix.env}}
