name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build_package:
    name: Build and test with ${{ matrix.distro }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        distro:
          - melodic
          - noetic
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@0.3.3
        with:
          package-name: spatial_audio_demo
          target-ros1-distro: ${{ matrix.distro }} 
