#
uint8 ADD=1
uint8 DELETE=2
uint8 DELETEALL=3
uint8 STOP=4
uint8 PLAY=5

# Req
Header header
int32 id

int32 action

geometry_msgs/Pose pose

string stream_topic_audio
string stream_topic_info

---
# Res
bool is_success
